[2021-06-28 17:03:00,004] [211361] [INFO] - record_capture.start_capture (record_capture.py:184) - 开始录音数据获取及推送
[2021-06-28 17:03:00,006] [211361] [INFO] - record_capture.append_failed (record_capture.py:221) - 开始重推失败数据
[2021-06-28 17:03:00,008] [211361] [INFO] - record_capture.get_data_from_file (record_capture.py:47) - 路径不存在：record_file/2021-06-27
[2021-06-28 17:03:00,048] [211361] [INFO] - record_capture.start_capture (record_capture.py:192) - 无数据需要推送，程序结束...
[2021-06-28 17:04:00,007] [211361] [INFO] - record_capture.start_capture (record_capture.py:184) - 开始录音数据获取及推送
[2021-06-28 17:04:00,015] [211361] [INFO] - record_capture.append_failed (record_capture.py:221) - 开始重推失败数据
[2021-06-28 17:04:00,016] [211361] [INFO] - record_capture.get_data_from_file (record_capture.py:47) - 路径不存在：record_file/2021-06-27
[2021-06-28 17:04:00,037] [211361] [INFO] - record_capture.start_capture (record_capture.py:192) - 无数据需要推送，程序结束...
[2021-06-28 17:05:00,012] [211361] [INFO] - record_capture.start_capture (record_capture.py:184) - 开始录音数据获取及推送
[2021-06-28 17:05:00,016] [211361] [INFO] - record_capture.append_failed (record_capture.py:221) - 开始重推失败数据
[2021-06-28 17:05:00,016] [211361] [INFO] - record_capture.get_data_from_file (record_capture.py:47) - 路径不存在：record_file/2021-06-27
[2021-06-28 17:05:00,036] [211361] [INFO] - record_capture.start_capture (record_capture.py:192) - 无数据需要推送，程序结束...
[2021-06-28 17:06:00,009] [211361] [INFO] - record_capture.start_capture (record_capture.py:184) - 开始录音数据获取及推送
[2021-06-28 17:06:00,013] [211361] [INFO] - record_capture.append_failed (record_capture.py:221) - 开始重推失败数据
[2021-06-28 17:06:00,013] [211361] [INFO] - record_capture.get_data_from_file (record_capture.py:47) - 路径不存在：record_file/2021-06-27
[2021-06-28 17:06:00,036] [211361] [INFO] - record_capture.start_capture (record_capture.py:192) - 无数据需要推送，程序结束...
[2021-06-28 17:07:00,008] [211361] [INFO] - record_capture.start_capture (record_capture.py:184) - 开始录音数据获取及推送
[2021-06-28 17:07:00,011] [211361] [INFO] - record_capture.append_failed (record_capture.py:221) - 开始重推失败数据
[2021-06-28 17:07:00,012] [211361] [INFO] - record_capture.get_data_from_file (record_capture.py:47) - 路径不存在：record_file/2021-06-27
[2021-06-28 17:07:00,044] [211361] [INFO] - record_capture.start_capture (record_capture.py:192) - 无数据需要推送，程序结束...
